# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rails-validators"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-04-18"
  s.description = "Reusable validators"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".DS_Store",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/generators/rails_validators/rails_validators_generator.rb",
    "lib/rails-validators.rb",
    "lib/rails-validators/account_number_validator.rb",
    "lib/rails-validators/alpha_name_validator.rb",
    "lib/rails-validators/company_name_validator.rb",
    "lib/rails-validators/currency_validator.rb",
    "lib/rails-validators/dash_name_validator.rb",
    "lib/rails-validators/email_format_validator.rb",
    "lib/rails-validators/email_validator.rb",
    "lib/rails-validators/full_name_validator.rb",
    "lib/rails-validators/helper/validator_name_config.rb",
    "lib/rails-validators/name_validator.rb",
    "lib/rails-validators/person_name_validator.rb",
    "lib/rails-validators/ruby_name_validator.rb",
    "lib/rails-validators/url_format_validator.rb",
    "spec/rails-validators/generators/rails_validators_spec.rb",
    "spec/rails-validators_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/rails-validators"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.22"
  s.summary = "Common Rails 3 validators"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0.4"])
      s.add_runtime_dependency(%q<mail>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["> 1.2.3"])
      s.add_development_dependency(%q<generator-spec>, ["> 0.7.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, [">= 1.6.1"])
      s.add_dependency(%q<simplecov>, [">= 0.4"])
      s.add_dependency(%q<mail>, [">= 0"])
      s.add_dependency(%q<rspec>, ["> 1.2.3"])
      s.add_dependency(%q<generator-spec>, ["> 0.7.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.1.0"])
    s.add_dependency(%q<bundler>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, [">= 1.6.1"])
    s.add_dependency(%q<simplecov>, [">= 0.4"])
    s.add_dependency(%q<mail>, [">= 0"])
    s.add_dependency(%q<rspec>, ["> 1.2.3"])
    s.add_dependency(%q<generator-spec>, ["> 0.7.0"])
  end
end

